name: delete-workflow-runs

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 60

jobs:
  del_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: bfren/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: 0
